name: Setup Rust Environment

inputs:
  key:
    description: Cache key
    required: true

runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ inputs.key }}-cargo-${{ hashFiles('Cargo.lock') }}
