language: rust

rust:
  - stable
  - nightly

branches:
  only:
    - staging
    - trying
    - master

matrix:
  include:
    - rust: stable
      script:
        - rustup component add rustfmt
        - cargo fmt -- --check

cache: cargo

script:
  - cargo test
  - cargo test --all-features
